name: PushGitlab

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      

    - name: Push To Gitlab
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "csword123001"
        git config user.email "csword001@dundee.ac.uk"
        git remote set-url origin "https://oauth2:${token}@codeingress-test.hic.dundee.ac.uk/csword001/shdeploy1.git"
        git push origin master
