name: shuser3-2-mirror

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/<namespace>/<repository>"
      env:
        GITLAB_HOSTNAME: "codeingress-test.hic.dundee.ac.uk"
        GITLAB_USERNAME: "csword001"
        GITLAB_PASSWORD: ${{ UfNZuszvgcUfS_BNYUNn  }} 
        GITLAB_PROJECT_ID: "shuser2"
        GITHUB_TOKEN: ${{ 3df5b998b2deaf42b1811703ebf65b0ca736d5ce }} 
